export const ReportDisputeNoRep__cta: string;
export const reportDisputeNoRepCta: string;
export const buttonDisabled: string;
export const imperative: string;
export const navigational: string;
export const ReportDisputeNoRep: string;
export const reportDisputeNoRep: string;
export const ReportDisputeNoRep__message: string;
export const reportDisputeNoRepMessage: string;
