export const ReportingReportForm__fields: string;
export const reportingReportFormFields: string;
export const ReportingReport__RepAmount: string;
export const reportingReportRepAmount: string;
export const ReportingReportREP: string;
export const reportingReportRep: string;
export const reportingReportInsufficientFunds: string;
export const ReportingReport__outcome_selection_msg: string;
export const reportingReportOutcomeSelectionMsg: string;
