/**
 * Autogenerated from https://github.com/tinybike/augur-serpent/tree/master/serpent/function%20files
 * serpent mk_full_signature sendReputation.se
 */
module.exports = [{
    "name": "sendReputation(int256,int256,int256)",
    "type": "function",
    "inputs": [{ "name": "branch", "type": "int256" }, { "name": "recver", "type": "int256" }, { "name": "value", "type": "int256" }],
    "outputs": [{ "name": "out", "type": "int256" }]
}];
