#!/bin/bash
# run augur.js unit tests using mocha/it.each

trap "exit" INT

mocha test_connect.js
mocha test_fixedpoint.js
mocha test_encoder.js
mocha test_ethrpc.js
mocha test_invoke.js
mocha test_payments.js
mocha test_markets.js
mocha test_reporting.js
mocha test_expiring.js
mocha test_augur.js
mocha faucets.js
mocha setup_consensus.js
mocha test_interpolate.js
mocha test_dispatch.js
mocha test_score.js
mocha test_resolve.js
