#!/usr/bin/env sh

set -e;

echo $0

method="$1"

usage() {
  cat <<HERE
To start augur services:
./augur/cli start

To start GSN
./augur/cli start-gsn

To stop services:
./augur/cli stop

To restart services:
./augur/cli restart

To upgrade this script:
./augur/cli upgrade

HERE
}

if [ -z "${method}" ]; then
  usage
  exit 1
fi

case "$method" in
"start")
  printf "start augur sdk server\n";
  (
    cd augur &&\
    docker-compose up augur
  )
  ;;
"start-gsn")
  (
    cd augur &&\
    docker-compose up caddy gsn
  )
  ;;

"stop")
  (
    cd augur &&\
    docker-compose stop
  )
  ;;
"restart")
  (
    cd augur &&\
    docker-compose restart
  )
  ;;
"upgrade")
  printf "TODO\n";
  ;;
*)
  usage
  exit 1
esac
