// NOTE --  Each topic must be uniquely mapped to an icon
//          Each icon can have multiple topics via an array of strings
//          All values should be lowercase

const iconTopics = {
  'fa-copy': 'reporting',
  'fa-snowflake-o': 'snow',
  'fa-bolt': 'lightning',
  'fa-cloud': ['weather', 'rain', 'precipitation'],
  'fa-sun-o': ['climate', 'sunspot', 'sunspots', 'climate change', 'global warming'],
  'fa-thermometer': ['temperature', 'heat'],
  'fa-rocket': ['space', 'space program', 'rocket', 'nasa', 'spacex'],
  'fa-line-chart': ['finance', 'financial', 'financials', 'dow jones', 'to the moon', 'stock', 'stocks', 'derivative', 'derivatives', 'option', 'options', 'future', 'futures'],
  'fa-bug': ['antibiotic', 'antibiotics', 'bacteria', 'infection', 'infections', 'epidemic', 'epidemics'],
  'fa-ambulance': ['mortality', 'hospital', 'hospitals'],
  'fa-home': ['housing', 'home', 'realty'],
  'fa-industry': 'climate change',
  'fa-newspaper-o': ['news', 'events'],
  'fa-users': 'elections',
  'fa-ship': ['international trade', 'shipping'],
  'fa-music': ['music', 'songs', 'pop', 'rock', 'rap', 'dancing', 'dance', 'techno'],
  'fa-laptop': ['computers', 'computing', 'laptops'],
  'fa-lock': ['crypto', 'cryptography', 'encryption', 'security'],
  'fa-money': ['cryptocurrency', 'currency', 'currencies', 'money', 'value', 'fiat', 'debt', 'forex'],
  'fa-chain': ['blockchain', 'blockchains', 'block chain', 'block chains'],
  'fa-btc': ['bitcoin', 'btc', 'bitcoins'],
  'fa-usd': ['dollar', 'dollars', 'usd'],
  'fa-yen': ['yen', 'jpy', 'rmb', 'cny'],
  'fa-eur': ['euro', 'eur', 'euros'],
  'fa-rub': ['ruble', 'rubles', 'rub'],
  'fa-inr': ['inr', 'rupee', 'rupees'],
  'fa-superscript': ['math', 'mathematics', 'maths'],
  'fa-apple': ['apple', 'mac', 'osx', 'ios', 'ipad', 'steve jobs', 'tim cook'],
  'fa-futbol-o': ['futbol', 'soccer', 'world cup', 'football', 'sports'],
  'fa-shield': ['defense', 'national defense', 'military'],
  'fa-motorcycle': ['travel', 'traveling', 'motorcycles'],
  'fa-pie-chart': ['data', 'big data', 'analytics', 'statistics'],
  'fa-phone': ['phones', 'telephone', 'telephones'],
  'fa-mobile': ['smartphone', 'smartphones', 'smart phone', 'smart phones', 'android', 'iphone'],
  'fa-newspaper-o': ['news', 'newspaper', 'newspapers', 'fake news', 'media'],
  'fa-plug': ['electricity', 'electrical', 'power', 'power grid', 'electric'],
  'fa-plane': ['planes', 'airplane', 'airplanes', 'flying', 'flight', 'airport', 'airports', 'airline', 'airliner', 'jet'],
  'fa-flask': ['science', 'scientists', 'physics', 'chemistry', 'biology', 'genetics', 'chemical', 'chemicals'],
  'fa-cogs': ['engineering', 'engineers', 'manufacturing', 'manufacturers', 'steampunk', 'makers'],
  'fa-copyright': ['ip', 'intellectual property', 'copyleft', 'patents'],
  'fa-automobile': ['cars', 'automobiles', 'self-driving cars', 'accidents', 'crashes', 'driving', 'drivers', 'road rage'],
  'fa-beer': ['alcohol', 'alcoholics', 'drinking', 'beers'],
  'fa-briefcase': ['law', 'legal', 'laws', 'lawyers', 'legalese'],
  'fa-shopping-cart': ['e-commerce', 'commerce', 'shopping', 'consumers', 'customers'],
  'fa-university': ['banks', 'schools', 'universities', 'institutions', 'government', 'state', 'federal', 'bureaucracy'],
  'fa-truck': ['cargo', 'transport', 'transportation', 'trucks'],
  'fa-wrench': ['reliability', 'durability'],
  'fa-gavel': ['justice', 'courts', 'court system', 'judicial', 'supreme court', 'appeals court', 'superior court', 'trial', 'trials'],
  'fa-globe': ['earth', 'world', 'planet', 'planets', 'planetary'],
  'fa-key': ['vulnerability', 'vulnerabilities', 'backdoor', 'backdoors'],
  'fa-recycle': ['environment', 'environmental', 'environmentalism', 'recycling', 'green'],
  'fa-share-alt': ['network', 'networks', 'networking'],
  'fa-checkered': ['race', 'racing', 'races', 'horseracing', 'horserace', 'nascar'],
  'fa-at': ['email', 'emails', 'e-mail', 'e-mails', 'identity', 'names'],
  'fa-code': ['coding', 'programming', 'programmers', 'software', 'development', 'developers'],
  'fa-eye': ['surveillance', 'big brother', 'nsa', 'national security agency', 'snowden'],
  'fa-font-awesome': 'golf'
};

export default iconTopics;
