export const Wrapper: string;
export const wrapper: string;
export const Buy: string;
export const buy: string;
export const active: string;
export const Sell: string;
export const sell: string;
export const Scalar: string;
export const scalar: string;
