image: augurproject/gitlab-ci-base-node:latest

stages:
- build
- app_build
- test


before_script:
  - yarn install --ignore-scripts --frozen-lockfile
  - git config --global user.email "team@augur.net"
  - git config --global user.name "Augur Developers"

###
# Build

Build:
  stage: build
  cache:
    paths:
    - .yarn
  script:
  - lerna run build --stream --scope augur-core
  - lerna run build --stream --scope augur-node
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
    - node_modules
    - packages/*/node_modules
    - packages/augur-node/build
    - packages/augur-node/definitions
    - packages/augur-core/output

###
# Test
Node:
  stage: test
  script: lerna run test --stream --scope augur-node

"UI":
  stage: test
  script: lerna run test --stream --scope augur-ui

"Augur.js":
  stage: test
  script: lerna run test --stream --scope augur.js

.core: &test-core
  stage: test
  script: cd packages/augur-core && pytest -vv $tests

"Core - Trading and Libs":
  <<: *test-core
  variables:
    tests: tests/test*.py tests/libraries tests/trading

"Core - Reporting":
  <<: *test-core
  variables:
    tests: "tests/reporting"

"Core - Fuzzy":
  <<: *test-core
  variables:
   tests: "tests/fuzzy"

"Core - Unit":
  <<: *test-core
  variables:
    tests: "tests/unit"

###
# App Building
"Augur App":
  stage: app_build
  script:
    - lerna run make --scope augur-app
    - cd packages/augur-app && scripts/post_build.py
