#!/bin/bash
# nukes the site from orbit (it's the only way to be sure)

set -e
trap "exit" INT

# nuke
rm -Rf node_modules
if [ -f "app/app.js" ]; then
    rm app/app.js
fi

# rebuild
npm install
grunt browserify:build
grunt less

# run server
npm start
