/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { ParaOICashFactory } from "../ParaOICashFactory";

export class ParaOICashFactory__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ParaOICashFactory {
    return new Contract(address, _abi, signerOrProvider) as ParaOICashFactory;
  }
}

const _abi = [
  {
    constant: false,
    inputs: [
      {
        internalType: "contract IParaAugur",
        name: "_augur",
        type: "address",
      },
    ],
    name: "createParaOICash",
    outputs: [
      {
        internalType: "contract IParaOICash",
        name: "",
        type: "address",
      },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
];
