/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { ReputationTokenFactory } from "../ReputationTokenFactory";

export class ReputationTokenFactory__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ReputationTokenFactory {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ReputationTokenFactory;
  }
}

const _abi = [
  {
    constant: false,
    inputs: [
      {
        internalType: "contract IAugur",
        name: "_augur",
        type: "address",
      },
      {
        internalType: "contract IUniverse",
        name: "_parentUniverse",
        type: "address",
      },
    ],
    name: "createReputationToken",
    outputs: [
      {
        internalType: "contract IV2ReputationToken",
        name: "",
        type: "address",
      },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
];
