export const marketOutcomesListTableHeader: string;
export const MarketOutcomesList: string;
export const marketOutcomesList: string;
export const MarketOutcomesList__heading: string;
export const marketOutcomesListHeading: string;
export const MarketOutcomesList__table: string;
export const marketOutcomesListTable: string;
export const marketOutcomesListTableBody: string;
export const marketOutcomesListTableWrapper: string;
