version: '3.7'

services:
  https-portal:
    image: caddy:2.1.1-alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data
    restart: always
    environment:
      HOST: ${HOST}

  gsn:
    image: tabookey/gsn-dev-server:v0.4.1
    restart: always
    ports:
      - '8090:80' #needed for debugging without https frontend
    volumes:
      - ./gsndata:/app/data    #can be left out, to keep private-key inside the docker
    entrypoint: ["./RelayHttpServer", "-RelayHubAddress", "${RELAY_HUB}", "-Workdir", "$root/build/server", "-GasPricePercent", "${GAS_PRICE_PERCENT}", "-EthereumNodeUrl", "${NODE_URL}"]

