export const NO_RELAY = [
	'buyCompleteSets',
	'sellCompleteSets',
	'buy',
	'sell',
	'shortAsk',
	'trade',
	'short_sell',
	'commitTrade',
	'cancel',
	'submitReportHash',
	'submitReport',
	'register',
	'fundNewAccount',
	'send',
	'sendFrom',
	'sendReputation',
	'createSingleEventMarket'
];
