// Event names
export const APPROVAL = 'Approval'
export const BUY_COMPLETE_SETS = 'BuyCompleteSets'
export const CANCEL_ORDER = 'CancelOrder'
export const CREATE_MARKET = 'CreateMarket'
export const DEPOSIT_ETHER = 'DepositEther'
export const CREATE_ORDER = 'CreateOrder'
export const CLAIM_TRADING_PROCEEDS = 'ClaimTradingProceeds'
export const REDEEM_WINNING_TOKENS = 'RedeemWinningTokens'
export const SELL_COMPLETE_SETS = 'SellCompleteSets'
export const SUBMIT_REPORT = 'SubmitReport'
export const FILL_ORDER = 'FillOrder'
export const TRANSFER = 'Transfer'
export const WITHDRAW_ETHER = 'WithdrawEther'
export const CREATE_UNIVERSE = 'CreateUniverse'
export const SUBMIT_INITIAL_REPORT = 'SubmitInitialReport'
export const SUBMIT_DESIGNATED_REPORT = 'SubmitDesignatedReport'
export const DISPUTE_REPORTS = 'DisputeReports'
export const FINALIZE_MARKET = 'FinalizeMarket'
export const FORK_UNIVERSE = 'ForkUniverse'
export const MINT_TOKENS = 'MintTokens'
export const BURN_TOKENS = 'BurnTokens'
export const CREATE_FEE_WINDOW = 'CreateFeeWindow'
export const TRANSFER_INITIAL_REPORTER = 'TransferInitialReporter'
export const SET_TIMESTAMP = 'SetTimestamp'
export const CREATE_DISPUTE_CROWDSOURCER = 'CreateDisputeCrowdsourcer'
export const CONTRIBUTE_DISPUTE_CROWDSOURCER = 'ContributeDisputeCrowdsourcer'
export const REDEEM_INITIAL_REPORTER = 'RedeemInitialReporter'
export const REDEEM_DISPUTE_CROWDSOURCER = 'RedeemDisputeCrowdsourcer'
export const REDEEM_FEE_WINDOW = 'RedeemFeeWindow'

// for add-transactions.js
export const OPEN_ORDER = 'OpenOrder'
export const MARKET_CREATION = 'MarketCreation'
export const TRADE = 'Trade'
export const POSITION = 'Position'
export const REPORTING = 'Reporting'

// Other
export const TRANSFER_FUNDS = 'transfer_funds'
export const SENT_CASH = 'sent_cash'
export const SENT_ETHER = 'sent_ether'

// Trade/order labels
export const BUY = 'buy'
export const SELL = 'sell'
export const BID = 'bid'
export const ASK = 'ask'
export const MATCH_BID = 'match_bid'
export const MATCH_ASK = 'match_ask'
export const MARKET = 'market'
export const LIMIT = 'limit'
