version: '3'
services:
  augur-node-client:
    build: .
    image: augurproject/augur-node:dev
    links:
      - augur-node-server
    environment:
      - AUGUR_NODE_WS=ws://augur-node-server:9001
    depends_on:
      - augur-node-server
    entrypoint: /app/wait-for-url.sh http://augur-node-server:9001/status/sync npx mocha -r ts-node/register --inline-diffs "test/integration/**/*.ts"
  augur-node-server:
    build: .
    image: augurproject/augur-node:dev
    links:
      - geth
    environment:
      - ETHEREUM_HTTP=http://geth:8545
      - ETHEREUM_WS=ws://geth:8546
    depends_on:
      - geth
    entrypoint: /app/wait-for-url.sh http://geth:8545/ /app/docker-entrypoint.sh
  geth:
    image: augurproject/dev-pop-geth:core-1.0.0-13
