dist: trusty
sudo: required
language: node_js
services:
- docker
git:
  depth: 5
notifications:
  email: false
branches:
  only:
  - master
  - stable
  - mvp
  - petong/travis-ci
  - "/^v\\d+\\.\\d+\\.\\d+(-\\d+)?$/"
node_js:
- '8'
jobs:
  include:
  - stage: test travis-ci
    if: branch = petong/travis-ci
    script:
    - npm run lint
    -
    deploy:
      provider: script
      script: echo "I love travis yml"
      skip_cleanup: true
      on:
        all_branches: true
  - stage: deploy to dev
    if: branch = master
    script:
    - npm run lint
    - npm run coveralls
    deploy:
      provider: script
      script: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"; npm run docker:release -- dev
      skip_cleanup: true
      on:
        all_branches: true
  - stage: deploy to stable
    if: branch = stable
    script:
    - npm run lint
    - npm run coveralls
    deploy:
      provider: script
      script: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"; npm run docker:release -- stable
      skip_cleanup: true
      on:
        all_branches: true
env:
  global:
    - DOCKER_USERNAME=augurintegration
    - AWS_REGION=us-east-1
    - secure: "bHqDy2fmE3OP4f6q/7hawtEUk2hkrI6Vth/S+yjUmk4w5yX9U//V8r6XPk988AH5lAqbzFtC6f4H2HJDYrFZwEYBG9ZALmJftkyiXOTeRkWaLwHtfc+GoNnmhFxUvXN+iQk8Fza1gkJPfXi8zVTApB7oiRkjURfxAA3UF9wEJFW8n3nllm2dwW5LyLvphMY0kMwmyLccteI0UZx3pL9V1Lkt+dRsLMYBX24ccQ+nTfplray4UE7WgpsAiXyGTmIE8tVGR4JRgL/Mmg72IVfTHm21/1Q4nK47YuFlSnd6RAUUgJaVxhmMeAuBSXXwKOyNGWSy4ylg+LsNXx7oaZsr/D+vKxwa9CSe3yTitn25DP03xmhiyKuVsk73eyjsLdVtdf2LFHbyJzoY0RNKmkPsReyC42h0slrYp2dh0VeI2jhEXuDnScw77bpgNyPOkJBYXij/ibr7ybfHWm/AVpI+f7HWrZ+rc8m9BYlFh4IlQT4q0aEMeYbpytCF+hsyWxyaLY57U2HXQ85z76TCR73iDy+VLCavDVtkPybJmgWKgEUgfNed1zviuTZEk1gIl0CDb5X8VPuu3/n4Uvrmu1S8acRPcBBGYuqAYabHoPBEDX6oJcQ29GqiRZB9xnMfKzhLiHeP/STDPWZVVvzl0XofjrL2QLcRtdmSfA4cPT30GXM="
    - secure: "coLyQOwZ53Y0tx3oTVuTlko4vwhZgrWzDoFWb0URdOat7bRIF7r7lY7oVICNzIdln7/mFnuIIyySfwY/Lz2iBFgh7KZFyDMb3QsIHpFlHhqRT0S03wVpyrugKWyscfLtJ8EPvowLfyYHDoaJS/wmvjuzT8RASLdYS1t/izhG1k1c5lBoIwwgaZOBXf+FVCblvEOnMh2GCJ2bZLeHs/i2DxHEHEQ7i4rxYIbat1xzoGvI1wqeoiPj0oRIsQ7aIqSDbUWmdpIKvuYXX92Eky3rwIo0wndDSrgLEsFRRIcrDoH6LCM2dwVWXrhJCFM/B0xXOr3aYuxriMXmgkg3a63pdYBLLdtJPWSRZfleOExwtVQ9UPBnS8ZcTSv5JB6Sb6YYMlZHJxebtQ/nJTloo4+G0aebxuF7AfaFuxsZyK2L0pfS4EOG0p63xhhK2ehoFVwbw1WZFRkG9BFLtcQTGTyA+ICyt72/IwOP6jV59DS3913XErNnpE4PC4OP28mW60POZpwXuD2/pRNlofEjWBjyolJwTLwM1dw2QInW5925UKHi2Ay5EZs+011fYVq+Xjv8hftbVWV1Gg8ubQoIpb1K1klrCoq0IwEpeTtwmdQKV57g1UHj54pJ9gkaEpT52i41fG0J/82LZ1l9XIqiqOUri3Asbi+PHzKhH0UCv/0n+Ec="
    - secure: "TtmOsgQPEsMJNPnu0Cw3EmFLKo5jtgxvrCOorfTCpOhnxmvDwhjFfZCfgMYdyWrB59MsBIIzsQWeg2rJR6XNAvtKR7LHMdl1zMhwGVosrySZ2PRdZDhAdsLlcwgwrhu40si9M+1kTlBljuQn9dvzGxaHD/K81QwaFSKZdmf8FwcXwz+kY+yVPTNOSri/mg9gHf4r66pFKb36OcMI3HkLVqji/gI2vCsUIiENsCF5trfwrGDj/RtHeB8aJRY1z0YdwM44soFkvZooUwuNivQOkgKMED2CoiwRz4DTEVEw9gqN7Pb0dDXty/CJchgAM05iXH/YtHvoimBxT5fpzwoXC+htYGsk713fOX8QWFICzOP3ANuDuv119ob8w3ykHJ+pvjR0XkuAYkl+pwRXqSiQ58lhcnGW+xtwewAvz3ErDHsI0n1szdam4kAc0TLGthRyyOM8fOp6g2ECtaYzkTrjwgK9IWgNipQR4s8MKQs4KzJQf9BetpE4is8hjWla5+aiQv59tkvxuJSY0pGlkBd0GrgAsQrxhz/98kotpni8U11TWMOcuKvovvkQmx6OihN/vS2vgK3zEz2mK+OiSkmRwc9tparWE1rpSOPpKvVZ1C9KmLpp0MIO99pJ910Aove7B1Dx8UeUk7ptVJTx0TSSBCcUnCe4uWipLc3YVEfWXYc="
