export const DEFAULT = 'Decentralized Prediction Markets'

export const CREATE_MARKET = 'Create Market'
export const POSITIONS = 'Positions'
export const MARKET = 'Market'
export const MARKETS = 'Markets'
export const REPORTS = 'Reports'
export const TRANSACTIONS = 'Transactions'
export const ACCOUNT = 'Account'
export const AUTHENTICATION = 'Authentication'
