export const marketTradingFormButtonTrade: string;
export const marketTradingFormButtonMessage: string;
export const marketTradingFormDepositButton: string;
export const MarketTradingForm: string;
export const marketTradingForm: string;
export const marketTradingFormButtonOrderPlaced: string;
export const marketTradingFormInitialMessage: string;
export const MarketTradingForm__close: string;
export const marketTradingFormClose: string;
