export const AlertsView: string;
export const alertsView: string;
export const dark: string;
export const parent: string;
export const box: string;
export const close: string;
export const NullStateMessage: string;
export const nullStateMessage: string;
export const dismissContainer: string;
