export const REQUEST_LATEST_SYNCED_BLOCK = 'REQUEST_LATEST_SYNCED_BLOCK'
export const RESET_DATABASE = 'RESET_DATABASE'
export const START_AUGUR_NODE = 'START_AUGUR_NODE'
export const START_GETH = 'START_GETH'
export const START_UI_SERVER = 'START_UI_SERVER'
export const STOP_AUGUR_NODE = 'STOP_AUGUR_NODE'
export const STOP_GETH = 'STOP_GETH'

export const BULK_SYNC_FINISHED = 'BULK_SYNC_FINISHED'
export const BULK_SYNC_STARTED = 'BULK_SYNC_STARTED'
export const CLEAR_DB = 'CLEAR_DB'
export const CONSOLE_LOG = 'CONSOLE_LOG'
export const GETH_FINISHED_SYNCING = 'GETH_FINISHED_SYNCING'
export const LATEST_SYNCED_BLOCK = 'LATEST_SYNCED_BLOCK'
export const LATEST_SYNCED_GETH_BLOCK = 'LATEST_SYNCED_GETH_BLOCK'
export const ON_SERVER_CONNECTED = 'ON_SERVER_CONNECTED'
export const ON_SERVER_DISCONNECTED = 'ON_SERVER_DISCONNECTED'
export const ON_UI_SERVER_CONNECTED = 'ON_UI_SERVER_CONNECTED'
export const ON_UI_SERVER_DISCONNECTED = 'ON_UI_SERVER_DISCONNECTED'
export const PEER_COUNT_DATA = 'PEER_COUNT_DATA'
export const RESET_RESPONSE = 'RESET_RESPONSE'

// configuration file message types
export const SAVE_CONFIG = 'SAVE_CONFIG'
export const SAVE_CONFIG_RESPONSE = 'SAVE_CONFIG_RESPONSE'

export const REQUEST_CONFIG = 'REQUEST_CONFIG'
export const REQUEST_CONFIG_RESPONSE = 'REQUEST_CONFIG_RESPONSE'

// attributes
export const CONNECTED = 'CONNECTED'

export const INFO_NOTIFICATION = 'INFO_NOTIFICATION'
export const ERROR_NOTIFICATION = 'ERROR_NOTIFICATION'

export const UNEXPECTED_ERR = 'UNEXPECTED_ERR'
export const RESTARTING_MSG = 'RESTARTING_MSG'
export const START_FAILURE = 'START_FAILURE'
export const RUNNING_FAILURE = 'RUNNING_FAILURE'
export const RECONNECT_MSG = 'RECONNECT_MSG'
export const GETH_REMOTE_MSG = 'GETH_REMOTE_MSG'
export const APP_ERROR = 'APP_ERROR'
export const DATABASE_IN_USE = 'DATABASE_IN_USE'

export const PORT_IN_USE = 'PORT_IN_USE'
export const SSL_GEN_ERROR = 'SSL_GEN_ERROR'
export const SAVE_FAILURE = 'SAVE_FAILURE'
