export const REQUEST_LATEST_SYNCED_BLOCK = 'REQUEST_LATEST_SYNCED_BLOCK'
export const RESET_DATABASE = 'RESET_DATABASE'
export const START_AUGUR_NODE = 'START_AUGUR_NODE'
export const START_GETH = 'START_GETH'
export const START_UI_SERVER = 'START_UI_SERVER'
export const STOP_AUGUR_NODE = 'STOP_AUGUR_NODE'
export const STOP_GETH = 'STOP_GETH'

export const BULK_SYNC_FINISHED = 'BULK_SYNC_FINISHED'
export const BULK_SYNC_STARTED = 'BULK_SYNC_STARTED'
export const CLEAR_DB = 'CLEAR_DB'
export const CONSOLE_LOG = 'CONSOLE_LOG'
export const ERROR = 'ERROR'
export const GETH_FINISHED_SYNCING = 'GETH_FINISHED_SYNCING'
export const LATEST_SYNCED_BLOCK = 'LATEST_SYNCED_BLOCK'
export const LATEST_SYNCED_GETH_BLOCK = 'LATEST_SYNCED_GETH_BLOCK'
export const NO_RESET_DATABASE = 'NO_RESET_DATABASE'
export const ON_SERVER_CONNECTED = 'ON_SERVER_CONNECTED'
export const ON_SERVER_DISCONNECTED = 'ON_SERVER_DISCONNECTED'
export const ON_UI_SERVER_CONNECTED = 'ON_UI_SERVER_CONNECTED'
export const ON_UI_SERVER_DISCONNECTED = 'ON_UI_SERVER_DISCONNECTED'
export const PEER_COUNT_DATA = 'PEER_COUNT_DATA'
export const RESET_RESPONSE = 'RESET_RESPONSE'
export const SHOW_NOTICE = 'SHOW_NOTICE'
export const TOGGLE_SSL = 'TOGGLE_SSL'

// configuration file message types
export const SAVE_CONFIG = 'SAVE_CONFIG'
export const SAVE_CONFIG_RESPONSE = 'SAVE_CONFIG_RESPONSE'

export const REQUEST_CONFIG = 'REQUEST_CONFIG'
export const REQUEST_CONFIG_RESPONSE = 'REQUEST_CONFIG_RESPONSE'

// attributes
export const CONNECTED = 'CONNECTED'

