// events sent to main process
export const REBUILD_MENU = 'REBUILD_MENU'
export const REQUEST_CONFIG = 'REQUEST_CONFIG'
export const REQUEST_LATEST_SYNCED_BLOCK = 'REQUEST_LATEST_SYNCED_BLOCK'
export const RESET = 'RESET'
export const SAVE_NETWORK_CONFIG = 'SAVE_NETWORK_CONFIG'
export const START = 'START'
export const START_UI_SERVER = 'START_UI_SERVER'
export const STOP = 'STOP'
export const TOGGLE_GETH = 'TOGGLE_GETH'
export const TOGGLE_SSL_RESET = 'TOGGLE_SSL_RESET'

// events sent to render process
export const BULK_SYNC_FINISHED = 'BULK_SYNC_FINISHED'
export const BULK_SYNC_STARTED = 'BULK_SYNC_STARTED'
export const CLEAR_DB = 'CLEAR_DB'
export const CONFIG = 'CONFIG'
export const CONSOLE_LOG = 'CONSOLE_LOG'
export const ERROR = 'ERROR'
export const GETH_FINISHED_SYNCING = 'GETH_FINISHED_SYNCING'
export const LATEST_SYNCED_BLOCK = 'LATEST_SYNCED_BLOCK'
export const LATEST_SYNCED_GETH_BLOCK = 'LATEST_SYNCED_GETH_BLOCK'
export const NO_RESET_DATABASE = 'NO_RESET_DATABASE'
export const ON_SERVER_CONNECTED = 'ON_SERVER_CONNECTED'
export const ON_SERVER_DISCONNECTED = 'ON_SERVER_DISCONNECTED'
export const PEER_COUNT_DATA = 'PEER_COUNT_DATA'
export const RESET_RESPONSE = 'RESET_RESPONSE'
export const SAVE_NETWORK_CONFIG_RESPONSE = 'SAVE_NETWORK_CONFIG_RESPONSE'
export const SHOW_NOTICE = 'SHOW_NOTICE'
export const SSL = 'SSL'
export const TOGGLE_SSL = 'TOGGLE_SSL'

// network names
export const KOVAN = 'Kovan'
export const LIGHT_CLIENT = 'Local Light Node'
export const LOCAL = 'Local'
export const MAINNET = 'Mainnet'
export const RINKEBY = 'Rinkeby'
export const ROPSTEN = 'Ropsten'
