export const MarketPreview: string;
export const marketPreview: string;
export const details: string;
export const footer: string;
export const singleCard: string;
export const returns: string;
export const outcomes: string;
export const outcome: string;
export const outcomePrice: string;
