/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface CreateOrderInterface extends ethers.utils.Interface {
  functions: {
    "augur()": FunctionFragment;
    "augurTrading()": FunctionFragment;
    "cash()": FunctionFragment;
    "createOrder(address,uint8,uint256,uint256,address,uint256,bytes32,bytes32,bytes32)": FunctionFragment;
    "getInitialized()": FunctionFragment;
    "initialize(address,address)": FunctionFragment;
    "orders()": FunctionFragment;
    "profitLoss()": FunctionFragment;
    "publicCreateOrder(uint8,uint256,uint256,address,uint256,bytes32,bytes32,bytes32)": FunctionFragment;
    "publicCreateOrders(uint256[],uint8[],uint256[],uint256[],address,bytes32)": FunctionFragment;
    "trade()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "augur", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "augurTrading",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "cash", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "createOrder",
    values: [
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string,
      BigNumberish,
      BytesLike,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getInitialized",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "orders", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "profitLoss",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "publicCreateOrder",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string,
      BigNumberish,
      BytesLike,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "publicCreateOrders",
    values: [
      BigNumberish[],
      BigNumberish[],
      BigNumberish[],
      BigNumberish[],
      string,
      BytesLike
    ]
  ): string;
  encodeFunctionData(functionFragment: "trade", values?: undefined): string;

  decodeFunctionResult(functionFragment: "augur", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "augurTrading",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cash", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getInitialized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "orders", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "profitLoss", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "publicCreateOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "publicCreateOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "trade", data: BytesLike): Result;

  events: {};
}

export class CreateOrder extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  listeners<T, G>(
    eventFilter?: TypedEventFilter<T, G>
  ): Array<TypedListener<T, G>>;
  off<T, G>(
    eventFilter: TypedEventFilter<T, G>,
    listener: TypedListener<T, G>
  ): this;
  on<T, G>(
    eventFilter: TypedEventFilter<T, G>,
    listener: TypedListener<T, G>
  ): this;
  once<T, G>(
    eventFilter: TypedEventFilter<T, G>,
    listener: TypedListener<T, G>
  ): this;
  removeListener<T, G>(
    eventFilter: TypedEventFilter<T, G>,
    listener: TypedListener<T, G>
  ): this;
  removeAllListeners<T, G>(eventFilter: TypedEventFilter<T, G>): this;

  queryFilter<T, G>(
    event: TypedEventFilter<T, G>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<T & G>>>;

  interface: CreateOrderInterface;

  functions: {
    augur(overrides?: CallOverrides): Promise<[string]>;

    "augur()"(overrides?: CallOverrides): Promise<[string]>;

    augurTrading(overrides?: CallOverrides): Promise<[string]>;

    "augurTrading()"(overrides?: CallOverrides): Promise<[string]>;

    cash(overrides?: CallOverrides): Promise<[string]>;

    "cash()"(overrides?: CallOverrides): Promise<[string]>;

    createOrder(
      _creator: string,
      _type: BigNumberish,
      _attoshares: BigNumberish,
      _price: BigNumberish,
      _market: string,
      _outcome: BigNumberish,
      _betterOrderId: BytesLike,
      _worseOrderId: BytesLike,
      _tradeGroupId: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "createOrder(address,uint8,uint256,uint256,address,uint256,bytes32,bytes32,bytes32)"(
      _creator: string,
      _type: BigNumberish,
      _attoshares: BigNumberish,
      _price: BigNumberish,
      _market: string,
      _outcome: BigNumberish,
      _betterOrderId: BytesLike,
      _worseOrderId: BytesLike,
      _tradeGroupId: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getInitialized(overrides?: CallOverrides): Promise<[boolean]>;

    "getInitialized()"(overrides?: CallOverrides): Promise<[boolean]>;

    initialize(
      _augur: string,
      _augurTrading: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "initialize(address,address)"(
      _augur: string,
      _augurTrading: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    orders(overrides?: CallOverrides): Promise<[string]>;

    "orders()"(overrides?: CallOverrides): Promise<[string]>;

    profitLoss(overrides?: CallOverrides): Promise<[string]>;

    "profitLoss()"(overrides?: CallOverrides): Promise<[string]>;

    publicCreateOrder(
      _type: BigNumberish,
      _attoshares: BigNumberish,
      _price: BigNumberish,
      _market: string,
      _outcome: BigNumberish,
      _betterOrderId: BytesLike,
      _worseOrderId: BytesLike,
      _tradeGroupId: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "publicCreateOrder(uint8,uint256,uint256,address,uint256,bytes32,bytes32,bytes32)"(
      _type: BigNumberish,
      _attoshares: BigNumberish,
      _price: BigNumberish,
      _market: string,
      _outcome: BigNumberish,
      _betterOrderId: BytesLike,
      _worseOrderId: BytesLike,
      _tradeGroupId: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    publicCreateOrders(
      _outcomes: BigNumberish[],
      _types: BigNumberish[],
      _attoshareAmounts: BigNumberish[],
      _prices: BigNumberish[],
      _market: string,
      _tradeGroupId: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "publicCreateOrders(uint256[],uint8[],uint256[],uint256[],address,bytes32)"(
      _outcomes: BigNumberish[],
      _types: BigNumberish[],
      _attoshareAmounts: BigNumberish[],
      _prices: BigNumberish[],
      _market: string,
      _tradeGroupId: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    trade(overrides?: CallOverrides): Promise<[string]>;

    "trade()"(overrides?: CallOverrides): Promise<[string]>;
  };

  augur(overrides?: CallOverrides): Promise<string>;

  "augur()"(overrides?: CallOverrides): Promise<string>;

  augurTrading(overrides?: CallOverrides): Promise<string>;

  "augurTrading()"(overrides?: CallOverrides): Promise<string>;

  cash(overrides?: CallOverrides): Promise<string>;

  "cash()"(overrides?: CallOverrides): Promise<string>;

  createOrder(
    _creator: string,
    _type: BigNumberish,
    _attoshares: BigNumberish,
    _price: BigNumberish,
    _market: string,
    _outcome: BigNumberish,
    _betterOrderId: BytesLike,
    _worseOrderId: BytesLike,
    _tradeGroupId: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "createOrder(address,uint8,uint256,uint256,address,uint256,bytes32,bytes32,bytes32)"(
    _creator: string,
    _type: BigNumberish,
    _attoshares: BigNumberish,
    _price: BigNumberish,
    _market: string,
    _outcome: BigNumberish,
    _betterOrderId: BytesLike,
    _worseOrderId: BytesLike,
    _tradeGroupId: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getInitialized(overrides?: CallOverrides): Promise<boolean>;

  "getInitialized()"(overrides?: CallOverrides): Promise<boolean>;

  initialize(
    _augur: string,
    _augurTrading: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "initialize(address,address)"(
    _augur: string,
    _augurTrading: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  orders(overrides?: CallOverrides): Promise<string>;

  "orders()"(overrides?: CallOverrides): Promise<string>;

  profitLoss(overrides?: CallOverrides): Promise<string>;

  "profitLoss()"(overrides?: CallOverrides): Promise<string>;

  publicCreateOrder(
    _type: BigNumberish,
    _attoshares: BigNumberish,
    _price: BigNumberish,
    _market: string,
    _outcome: BigNumberish,
    _betterOrderId: BytesLike,
    _worseOrderId: BytesLike,
    _tradeGroupId: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "publicCreateOrder(uint8,uint256,uint256,address,uint256,bytes32,bytes32,bytes32)"(
    _type: BigNumberish,
    _attoshares: BigNumberish,
    _price: BigNumberish,
    _market: string,
    _outcome: BigNumberish,
    _betterOrderId: BytesLike,
    _worseOrderId: BytesLike,
    _tradeGroupId: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  publicCreateOrders(
    _outcomes: BigNumberish[],
    _types: BigNumberish[],
    _attoshareAmounts: BigNumberish[],
    _prices: BigNumberish[],
    _market: string,
    _tradeGroupId: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "publicCreateOrders(uint256[],uint8[],uint256[],uint256[],address,bytes32)"(
    _outcomes: BigNumberish[],
    _types: BigNumberish[],
    _attoshareAmounts: BigNumberish[],
    _prices: BigNumberish[],
    _market: string,
    _tradeGroupId: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  trade(overrides?: CallOverrides): Promise<string>;

  "trade()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    augur(overrides?: CallOverrides): Promise<string>;

    "augur()"(overrides?: CallOverrides): Promise<string>;

    augurTrading(overrides?: CallOverrides): Promise<string>;

    "augurTrading()"(overrides?: CallOverrides): Promise<string>;

    cash(overrides?: CallOverrides): Promise<string>;

    "cash()"(overrides?: CallOverrides): Promise<string>;

    createOrder(
      _creator: string,
      _type: BigNumberish,
      _attoshares: BigNumberish,
      _price: BigNumberish,
      _market: string,
      _outcome: BigNumberish,
      _betterOrderId: BytesLike,
      _worseOrderId: BytesLike,
      _tradeGroupId: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "createOrder(address,uint8,uint256,uint256,address,uint256,bytes32,bytes32,bytes32)"(
      _creator: string,
      _type: BigNumberish,
      _attoshares: BigNumberish,
      _price: BigNumberish,
      _market: string,
      _outcome: BigNumberish,
      _betterOrderId: BytesLike,
      _worseOrderId: BytesLike,
      _tradeGroupId: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    getInitialized(overrides?: CallOverrides): Promise<boolean>;

    "getInitialized()"(overrides?: CallOverrides): Promise<boolean>;

    initialize(
      _augur: string,
      _augurTrading: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "initialize(address,address)"(
      _augur: string,
      _augurTrading: string,
      overrides?: CallOverrides
    ): Promise<void>;

    orders(overrides?: CallOverrides): Promise<string>;

    "orders()"(overrides?: CallOverrides): Promise<string>;

    profitLoss(overrides?: CallOverrides): Promise<string>;

    "profitLoss()"(overrides?: CallOverrides): Promise<string>;

    publicCreateOrder(
      _type: BigNumberish,
      _attoshares: BigNumberish,
      _price: BigNumberish,
      _market: string,
      _outcome: BigNumberish,
      _betterOrderId: BytesLike,
      _worseOrderId: BytesLike,
      _tradeGroupId: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "publicCreateOrder(uint8,uint256,uint256,address,uint256,bytes32,bytes32,bytes32)"(
      _type: BigNumberish,
      _attoshares: BigNumberish,
      _price: BigNumberish,
      _market: string,
      _outcome: BigNumberish,
      _betterOrderId: BytesLike,
      _worseOrderId: BytesLike,
      _tradeGroupId: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    publicCreateOrders(
      _outcomes: BigNumberish[],
      _types: BigNumberish[],
      _attoshareAmounts: BigNumberish[],
      _prices: BigNumberish[],
      _market: string,
      _tradeGroupId: BytesLike,
      overrides?: CallOverrides
    ): Promise<string[]>;

    "publicCreateOrders(uint256[],uint8[],uint256[],uint256[],address,bytes32)"(
      _outcomes: BigNumberish[],
      _types: BigNumberish[],
      _attoshareAmounts: BigNumberish[],
      _prices: BigNumberish[],
      _market: string,
      _tradeGroupId: BytesLike,
      overrides?: CallOverrides
    ): Promise<string[]>;

    trade(overrides?: CallOverrides): Promise<string>;

    "trade()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    augur(overrides?: CallOverrides): Promise<BigNumber>;

    "augur()"(overrides?: CallOverrides): Promise<BigNumber>;

    augurTrading(overrides?: CallOverrides): Promise<BigNumber>;

    "augurTrading()"(overrides?: CallOverrides): Promise<BigNumber>;

    cash(overrides?: CallOverrides): Promise<BigNumber>;

    "cash()"(overrides?: CallOverrides): Promise<BigNumber>;

    createOrder(
      _creator: string,
      _type: BigNumberish,
      _attoshares: BigNumberish,
      _price: BigNumberish,
      _market: string,
      _outcome: BigNumberish,
      _betterOrderId: BytesLike,
      _worseOrderId: BytesLike,
      _tradeGroupId: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "createOrder(address,uint8,uint256,uint256,address,uint256,bytes32,bytes32,bytes32)"(
      _creator: string,
      _type: BigNumberish,
      _attoshares: BigNumberish,
      _price: BigNumberish,
      _market: string,
      _outcome: BigNumberish,
      _betterOrderId: BytesLike,
      _worseOrderId: BytesLike,
      _tradeGroupId: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    getInitialized(overrides?: CallOverrides): Promise<BigNumber>;

    "getInitialized()"(overrides?: CallOverrides): Promise<BigNumber>;

    initialize(
      _augur: string,
      _augurTrading: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "initialize(address,address)"(
      _augur: string,
      _augurTrading: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    orders(overrides?: CallOverrides): Promise<BigNumber>;

    "orders()"(overrides?: CallOverrides): Promise<BigNumber>;

    profitLoss(overrides?: CallOverrides): Promise<BigNumber>;

    "profitLoss()"(overrides?: CallOverrides): Promise<BigNumber>;

    publicCreateOrder(
      _type: BigNumberish,
      _attoshares: BigNumberish,
      _price: BigNumberish,
      _market: string,
      _outcome: BigNumberish,
      _betterOrderId: BytesLike,
      _worseOrderId: BytesLike,
      _tradeGroupId: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "publicCreateOrder(uint8,uint256,uint256,address,uint256,bytes32,bytes32,bytes32)"(
      _type: BigNumberish,
      _attoshares: BigNumberish,
      _price: BigNumberish,
      _market: string,
      _outcome: BigNumberish,
      _betterOrderId: BytesLike,
      _worseOrderId: BytesLike,
      _tradeGroupId: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    publicCreateOrders(
      _outcomes: BigNumberish[],
      _types: BigNumberish[],
      _attoshareAmounts: BigNumberish[],
      _prices: BigNumberish[],
      _market: string,
      _tradeGroupId: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "publicCreateOrders(uint256[],uint8[],uint256[],uint256[],address,bytes32)"(
      _outcomes: BigNumberish[],
      _types: BigNumberish[],
      _attoshareAmounts: BigNumberish[],
      _prices: BigNumberish[],
      _market: string,
      _tradeGroupId: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    trade(overrides?: CallOverrides): Promise<BigNumber>;

    "trade()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    augur(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "augur()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    augurTrading(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "augurTrading()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    cash(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "cash()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    createOrder(
      _creator: string,
      _type: BigNumberish,
      _attoshares: BigNumberish,
      _price: BigNumberish,
      _market: string,
      _outcome: BigNumberish,
      _betterOrderId: BytesLike,
      _worseOrderId: BytesLike,
      _tradeGroupId: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "createOrder(address,uint8,uint256,uint256,address,uint256,bytes32,bytes32,bytes32)"(
      _creator: string,
      _type: BigNumberish,
      _attoshares: BigNumberish,
      _price: BigNumberish,
      _market: string,
      _outcome: BigNumberish,
      _betterOrderId: BytesLike,
      _worseOrderId: BytesLike,
      _tradeGroupId: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    getInitialized(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getInitialized()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      _augur: string,
      _augurTrading: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "initialize(address,address)"(
      _augur: string,
      _augurTrading: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    orders(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "orders()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    profitLoss(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "profitLoss()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    publicCreateOrder(
      _type: BigNumberish,
      _attoshares: BigNumberish,
      _price: BigNumberish,
      _market: string,
      _outcome: BigNumberish,
      _betterOrderId: BytesLike,
      _worseOrderId: BytesLike,
      _tradeGroupId: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "publicCreateOrder(uint8,uint256,uint256,address,uint256,bytes32,bytes32,bytes32)"(
      _type: BigNumberish,
      _attoshares: BigNumberish,
      _price: BigNumberish,
      _market: string,
      _outcome: BigNumberish,
      _betterOrderId: BytesLike,
      _worseOrderId: BytesLike,
      _tradeGroupId: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    publicCreateOrders(
      _outcomes: BigNumberish[],
      _types: BigNumberish[],
      _attoshareAmounts: BigNumberish[],
      _prices: BigNumberish[],
      _market: string,
      _tradeGroupId: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "publicCreateOrders(uint256[],uint8[],uint256[],uint256[],address,bytes32)"(
      _outcomes: BigNumberish[],
      _types: BigNumberish[],
      _attoshareAmounts: BigNumberish[],
      _prices: BigNumberish[],
      _market: string,
      _tradeGroupId: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    trade(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "trade()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
