/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface MultiAssetProxyInterface extends ethers.utils.Interface {
  functions: {
    "addAuthorizedAddress(address)": FunctionFragment;
    "assetProxies(bytes4)": FunctionFragment;
    "authorities(uint256)": FunctionFragment;
    "authorized(address)": FunctionFragment;
    "getAssetProxy(bytes4)": FunctionFragment;
    "getAuthorizedAddresses()": FunctionFragment;
    "getProxyId()": FunctionFragment;
    "owner()": FunctionFragment;
    "registerAssetProxy(address)": FunctionFragment;
    "removeAuthorizedAddress(address)": FunctionFragment;
    "removeAuthorizedAddressAtIndex(address,uint256)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "addAuthorizedAddress",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "assetProxies",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorities",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "authorized", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getAssetProxy",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAuthorizedAddresses",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getProxyId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerAssetProxy",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "removeAuthorizedAddress",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "removeAuthorizedAddressAtIndex",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "addAuthorizedAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "assetProxies",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorities",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "authorized", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAssetProxy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAuthorizedAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getProxyId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerAssetProxy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeAuthorizedAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeAuthorizedAddressAtIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "AssetProxyRegistered(bytes4,address)": EventFragment;
    "AuthorizedAddressAdded(address,address)": EventFragment;
    "AuthorizedAddressRemoved(address,address)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AssetProxyRegistered"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AuthorizedAddressAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AuthorizedAddressRemoved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export class MultiAssetProxy extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  listeners<T, G>(
    eventFilter?: TypedEventFilter<T, G>
  ): Array<TypedListener<T, G>>;
  off<T, G>(
    eventFilter: TypedEventFilter<T, G>,
    listener: TypedListener<T, G>
  ): this;
  on<T, G>(
    eventFilter: TypedEventFilter<T, G>,
    listener: TypedListener<T, G>
  ): this;
  once<T, G>(
    eventFilter: TypedEventFilter<T, G>,
    listener: TypedListener<T, G>
  ): this;
  removeListener<T, G>(
    eventFilter: TypedEventFilter<T, G>,
    listener: TypedListener<T, G>
  ): this;
  removeAllListeners<T, G>(eventFilter: TypedEventFilter<T, G>): this;

  queryFilter<T, G>(
    event: TypedEventFilter<T, G>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<T & G>>>;

  interface: MultiAssetProxyInterface;

  functions: {
    addAuthorizedAddress(
      target: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "addAuthorizedAddress(address)"(
      target: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    assetProxies(arg0: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    "assetProxies(bytes4)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    authorities(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "authorities(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    authorized(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;

    "authorized(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    getAssetProxy(
      assetProxyId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "getAssetProxy(bytes4)"(
      assetProxyId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getAuthorizedAddresses(overrides?: CallOverrides): Promise<[string[]]>;

    "getAuthorizedAddresses()"(overrides?: CallOverrides): Promise<[string[]]>;

    getProxyId(overrides?: CallOverrides): Promise<[string]>;

    "getProxyId()"(overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    "owner()"(overrides?: CallOverrides): Promise<[string]>;

    registerAssetProxy(
      assetProxy: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "registerAssetProxy(address)"(
      assetProxy: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    removeAuthorizedAddress(
      target: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "removeAuthorizedAddress(address)"(
      target: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    removeAuthorizedAddressAtIndex(
      target: string,
      index: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "removeAuthorizedAddressAtIndex(address,uint256)"(
      target: string,
      index: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  addAuthorizedAddress(
    target: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "addAuthorizedAddress(address)"(
    target: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  assetProxies(arg0: BytesLike, overrides?: CallOverrides): Promise<string>;

  "assetProxies(bytes4)"(
    arg0: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  authorities(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  "authorities(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  authorized(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  "authorized(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  getAssetProxy(
    assetProxyId: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  "getAssetProxy(bytes4)"(
    assetProxyId: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  getAuthorizedAddresses(overrides?: CallOverrides): Promise<string[]>;

  "getAuthorizedAddresses()"(overrides?: CallOverrides): Promise<string[]>;

  getProxyId(overrides?: CallOverrides): Promise<string>;

  "getProxyId()"(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  "owner()"(overrides?: CallOverrides): Promise<string>;

  registerAssetProxy(
    assetProxy: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "registerAssetProxy(address)"(
    assetProxy: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  removeAuthorizedAddress(
    target: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "removeAuthorizedAddress(address)"(
    target: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  removeAuthorizedAddressAtIndex(
    target: string,
    index: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "removeAuthorizedAddressAtIndex(address,uint256)"(
    target: string,
    index: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "transferOwnership(address)"(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    addAuthorizedAddress(
      target: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "addAuthorizedAddress(address)"(
      target: string,
      overrides?: CallOverrides
    ): Promise<void>;

    assetProxies(arg0: BytesLike, overrides?: CallOverrides): Promise<string>;

    "assetProxies(bytes4)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    authorities(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    "authorities(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    authorized(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    "authorized(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    getAssetProxy(
      assetProxyId: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "getAssetProxy(bytes4)"(
      assetProxyId: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    getAuthorizedAddresses(overrides?: CallOverrides): Promise<string[]>;

    "getAuthorizedAddresses()"(overrides?: CallOverrides): Promise<string[]>;

    getProxyId(overrides?: CallOverrides): Promise<string>;

    "getProxyId()"(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    "owner()"(overrides?: CallOverrides): Promise<string>;

    registerAssetProxy(
      assetProxy: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "registerAssetProxy(address)"(
      assetProxy: string,
      overrides?: CallOverrides
    ): Promise<void>;

    removeAuthorizedAddress(
      target: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "removeAuthorizedAddress(address)"(
      target: string,
      overrides?: CallOverrides
    ): Promise<void>;

    removeAuthorizedAddressAtIndex(
      target: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "removeAuthorizedAddressAtIndex(address,uint256)"(
      target: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    AssetProxyRegistered(
      id: null,
      assetProxy: null
    ): TypedEventFilter<[string, string], { id: string; assetProxy: string }>;

    AuthorizedAddressAdded(
      target: string | null,
      caller: string | null
    ): TypedEventFilter<[string, string], { target: string; caller: string }>;

    AuthorizedAddressRemoved(
      target: string | null,
      caller: string | null
    ): TypedEventFilter<[string, string], { target: string; caller: string }>;

    OwnershipTransferred(
      previousOwner: string | null,
      newOwner: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;
  };

  estimateGas: {
    addAuthorizedAddress(
      target: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "addAuthorizedAddress(address)"(
      target: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    assetProxies(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "assetProxies(bytes4)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    authorities(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "authorities(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    authorized(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "authorized(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAssetProxy(
      assetProxyId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getAssetProxy(bytes4)"(
      assetProxyId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAuthorizedAddresses(overrides?: CallOverrides): Promise<BigNumber>;

    "getAuthorizedAddresses()"(overrides?: CallOverrides): Promise<BigNumber>;

    getProxyId(overrides?: CallOverrides): Promise<BigNumber>;

    "getProxyId()"(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    "owner()"(overrides?: CallOverrides): Promise<BigNumber>;

    registerAssetProxy(
      assetProxy: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "registerAssetProxy(address)"(
      assetProxy: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    removeAuthorizedAddress(
      target: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "removeAuthorizedAddress(address)"(
      target: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    removeAuthorizedAddressAtIndex(
      target: string,
      index: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "removeAuthorizedAddressAtIndex(address,uint256)"(
      target: string,
      index: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addAuthorizedAddress(
      target: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "addAuthorizedAddress(address)"(
      target: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    assetProxies(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "assetProxies(bytes4)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    authorities(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "authorities(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    authorized(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "authorized(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAssetProxy(
      assetProxyId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getAssetProxy(bytes4)"(
      assetProxyId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAuthorizedAddresses(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getAuthorizedAddresses()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getProxyId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getProxyId()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "owner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    registerAssetProxy(
      assetProxy: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "registerAssetProxy(address)"(
      assetProxy: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    removeAuthorizedAddress(
      target: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "removeAuthorizedAddress(address)"(
      target: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    removeAuthorizedAddressAtIndex(
      target: string,
      index: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "removeAuthorizedAddressAtIndex(address,uint256)"(
      target: string,
      index: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
