/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface TradeInterface extends ethers.utils.Interface {
  functions: {
    "augur()": FunctionFragment;
    "augurTrading()": FunctionFragment;
    "cash()": FunctionFragment;
    "createOrder()": FunctionFragment;
    "fillOrder()": FunctionFragment;
    "getInitialized()": FunctionFragment;
    "initialize(address,address)": FunctionFragment;
    "orders()": FunctionFragment;
    "publicFillBestOrder(uint8,address,uint256,uint256,uint256,bytes32,uint256,bytes32)": FunctionFragment;
    "publicTrade(uint8,address,uint256,uint256,uint256,bytes32,bytes32,bytes32,uint256,bytes32)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "augur", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "augurTrading",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "cash", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "createOrder",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "fillOrder", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getInitialized",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "orders", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "publicFillBestOrder",
    values: [
      BigNumberish,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "publicTrade",
    values: [
      BigNumberish,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike,
      BytesLike,
      BigNumberish,
      BytesLike
    ]
  ): string;

  decodeFunctionResult(functionFragment: "augur", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "augurTrading",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cash", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fillOrder", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getInitialized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "orders", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "publicFillBestOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "publicTrade",
    data: BytesLike
  ): Result;

  events: {};
}

export class Trade extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  listeners<T, G>(
    eventFilter?: TypedEventFilter<T, G>
  ): Array<TypedListener<T, G>>;
  off<T, G>(
    eventFilter: TypedEventFilter<T, G>,
    listener: TypedListener<T, G>
  ): this;
  on<T, G>(
    eventFilter: TypedEventFilter<T, G>,
    listener: TypedListener<T, G>
  ): this;
  once<T, G>(
    eventFilter: TypedEventFilter<T, G>,
    listener: TypedListener<T, G>
  ): this;
  removeListener<T, G>(
    eventFilter: TypedEventFilter<T, G>,
    listener: TypedListener<T, G>
  ): this;
  removeAllListeners<T, G>(eventFilter: TypedEventFilter<T, G>): this;

  queryFilter<T, G>(
    event: TypedEventFilter<T, G>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<T & G>>>;

  interface: TradeInterface;

  functions: {
    augur(overrides?: CallOverrides): Promise<[string]>;

    "augur()"(overrides?: CallOverrides): Promise<[string]>;

    augurTrading(overrides?: CallOverrides): Promise<[string]>;

    "augurTrading()"(overrides?: CallOverrides): Promise<[string]>;

    cash(overrides?: CallOverrides): Promise<[string]>;

    "cash()"(overrides?: CallOverrides): Promise<[string]>;

    createOrder(overrides?: CallOverrides): Promise<[string]>;

    "createOrder()"(overrides?: CallOverrides): Promise<[string]>;

    fillOrder(overrides?: CallOverrides): Promise<[string]>;

    "fillOrder()"(overrides?: CallOverrides): Promise<[string]>;

    getInitialized(overrides?: CallOverrides): Promise<[boolean]>;

    "getInitialized()"(overrides?: CallOverrides): Promise<[boolean]>;

    initialize(
      _augur: string,
      _augurTrading: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "initialize(address,address)"(
      _augur: string,
      _augurTrading: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    orders(overrides?: CallOverrides): Promise<[string]>;

    "orders()"(overrides?: CallOverrides): Promise<[string]>;

    publicFillBestOrder(
      _direction: BigNumberish,
      _market: string,
      _outcome: BigNumberish,
      _amount: BigNumberish,
      _price: BigNumberish,
      _tradeGroupId: BytesLike,
      _loopLimit: BigNumberish,
      _fingerprint: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "publicFillBestOrder(uint8,address,uint256,uint256,uint256,bytes32,uint256,bytes32)"(
      _direction: BigNumberish,
      _market: string,
      _outcome: BigNumberish,
      _amount: BigNumberish,
      _price: BigNumberish,
      _tradeGroupId: BytesLike,
      _loopLimit: BigNumberish,
      _fingerprint: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    publicTrade(
      _direction: BigNumberish,
      _market: string,
      _outcome: BigNumberish,
      _amount: BigNumberish,
      _price: BigNumberish,
      _betterOrderId: BytesLike,
      _worseOrderId: BytesLike,
      _tradeGroupId: BytesLike,
      _loopLimit: BigNumberish,
      _fingerprint: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "publicTrade(uint8,address,uint256,uint256,uint256,bytes32,bytes32,bytes32,uint256,bytes32)"(
      _direction: BigNumberish,
      _market: string,
      _outcome: BigNumberish,
      _amount: BigNumberish,
      _price: BigNumberish,
      _betterOrderId: BytesLike,
      _worseOrderId: BytesLike,
      _tradeGroupId: BytesLike,
      _loopLimit: BigNumberish,
      _fingerprint: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  augur(overrides?: CallOverrides): Promise<string>;

  "augur()"(overrides?: CallOverrides): Promise<string>;

  augurTrading(overrides?: CallOverrides): Promise<string>;

  "augurTrading()"(overrides?: CallOverrides): Promise<string>;

  cash(overrides?: CallOverrides): Promise<string>;

  "cash()"(overrides?: CallOverrides): Promise<string>;

  createOrder(overrides?: CallOverrides): Promise<string>;

  "createOrder()"(overrides?: CallOverrides): Promise<string>;

  fillOrder(overrides?: CallOverrides): Promise<string>;

  "fillOrder()"(overrides?: CallOverrides): Promise<string>;

  getInitialized(overrides?: CallOverrides): Promise<boolean>;

  "getInitialized()"(overrides?: CallOverrides): Promise<boolean>;

  initialize(
    _augur: string,
    _augurTrading: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "initialize(address,address)"(
    _augur: string,
    _augurTrading: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  orders(overrides?: CallOverrides): Promise<string>;

  "orders()"(overrides?: CallOverrides): Promise<string>;

  publicFillBestOrder(
    _direction: BigNumberish,
    _market: string,
    _outcome: BigNumberish,
    _amount: BigNumberish,
    _price: BigNumberish,
    _tradeGroupId: BytesLike,
    _loopLimit: BigNumberish,
    _fingerprint: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "publicFillBestOrder(uint8,address,uint256,uint256,uint256,bytes32,uint256,bytes32)"(
    _direction: BigNumberish,
    _market: string,
    _outcome: BigNumberish,
    _amount: BigNumberish,
    _price: BigNumberish,
    _tradeGroupId: BytesLike,
    _loopLimit: BigNumberish,
    _fingerprint: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  publicTrade(
    _direction: BigNumberish,
    _market: string,
    _outcome: BigNumberish,
    _amount: BigNumberish,
    _price: BigNumberish,
    _betterOrderId: BytesLike,
    _worseOrderId: BytesLike,
    _tradeGroupId: BytesLike,
    _loopLimit: BigNumberish,
    _fingerprint: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "publicTrade(uint8,address,uint256,uint256,uint256,bytes32,bytes32,bytes32,uint256,bytes32)"(
    _direction: BigNumberish,
    _market: string,
    _outcome: BigNumberish,
    _amount: BigNumberish,
    _price: BigNumberish,
    _betterOrderId: BytesLike,
    _worseOrderId: BytesLike,
    _tradeGroupId: BytesLike,
    _loopLimit: BigNumberish,
    _fingerprint: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    augur(overrides?: CallOverrides): Promise<string>;

    "augur()"(overrides?: CallOverrides): Promise<string>;

    augurTrading(overrides?: CallOverrides): Promise<string>;

    "augurTrading()"(overrides?: CallOverrides): Promise<string>;

    cash(overrides?: CallOverrides): Promise<string>;

    "cash()"(overrides?: CallOverrides): Promise<string>;

    createOrder(overrides?: CallOverrides): Promise<string>;

    "createOrder()"(overrides?: CallOverrides): Promise<string>;

    fillOrder(overrides?: CallOverrides): Promise<string>;

    "fillOrder()"(overrides?: CallOverrides): Promise<string>;

    getInitialized(overrides?: CallOverrides): Promise<boolean>;

    "getInitialized()"(overrides?: CallOverrides): Promise<boolean>;

    initialize(
      _augur: string,
      _augurTrading: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "initialize(address,address)"(
      _augur: string,
      _augurTrading: string,
      overrides?: CallOverrides
    ): Promise<void>;

    orders(overrides?: CallOverrides): Promise<string>;

    "orders()"(overrides?: CallOverrides): Promise<string>;

    publicFillBestOrder(
      _direction: BigNumberish,
      _market: string,
      _outcome: BigNumberish,
      _amount: BigNumberish,
      _price: BigNumberish,
      _tradeGroupId: BytesLike,
      _loopLimit: BigNumberish,
      _fingerprint: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "publicFillBestOrder(uint8,address,uint256,uint256,uint256,bytes32,uint256,bytes32)"(
      _direction: BigNumberish,
      _market: string,
      _outcome: BigNumberish,
      _amount: BigNumberish,
      _price: BigNumberish,
      _tradeGroupId: BytesLike,
      _loopLimit: BigNumberish,
      _fingerprint: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    publicTrade(
      _direction: BigNumberish,
      _market: string,
      _outcome: BigNumberish,
      _amount: BigNumberish,
      _price: BigNumberish,
      _betterOrderId: BytesLike,
      _worseOrderId: BytesLike,
      _tradeGroupId: BytesLike,
      _loopLimit: BigNumberish,
      _fingerprint: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "publicTrade(uint8,address,uint256,uint256,uint256,bytes32,bytes32,bytes32,uint256,bytes32)"(
      _direction: BigNumberish,
      _market: string,
      _outcome: BigNumberish,
      _amount: BigNumberish,
      _price: BigNumberish,
      _betterOrderId: BytesLike,
      _worseOrderId: BytesLike,
      _tradeGroupId: BytesLike,
      _loopLimit: BigNumberish,
      _fingerprint: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    augur(overrides?: CallOverrides): Promise<BigNumber>;

    "augur()"(overrides?: CallOverrides): Promise<BigNumber>;

    augurTrading(overrides?: CallOverrides): Promise<BigNumber>;

    "augurTrading()"(overrides?: CallOverrides): Promise<BigNumber>;

    cash(overrides?: CallOverrides): Promise<BigNumber>;

    "cash()"(overrides?: CallOverrides): Promise<BigNumber>;

    createOrder(overrides?: CallOverrides): Promise<BigNumber>;

    "createOrder()"(overrides?: CallOverrides): Promise<BigNumber>;

    fillOrder(overrides?: CallOverrides): Promise<BigNumber>;

    "fillOrder()"(overrides?: CallOverrides): Promise<BigNumber>;

    getInitialized(overrides?: CallOverrides): Promise<BigNumber>;

    "getInitialized()"(overrides?: CallOverrides): Promise<BigNumber>;

    initialize(
      _augur: string,
      _augurTrading: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "initialize(address,address)"(
      _augur: string,
      _augurTrading: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    orders(overrides?: CallOverrides): Promise<BigNumber>;

    "orders()"(overrides?: CallOverrides): Promise<BigNumber>;

    publicFillBestOrder(
      _direction: BigNumberish,
      _market: string,
      _outcome: BigNumberish,
      _amount: BigNumberish,
      _price: BigNumberish,
      _tradeGroupId: BytesLike,
      _loopLimit: BigNumberish,
      _fingerprint: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "publicFillBestOrder(uint8,address,uint256,uint256,uint256,bytes32,uint256,bytes32)"(
      _direction: BigNumberish,
      _market: string,
      _outcome: BigNumberish,
      _amount: BigNumberish,
      _price: BigNumberish,
      _tradeGroupId: BytesLike,
      _loopLimit: BigNumberish,
      _fingerprint: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    publicTrade(
      _direction: BigNumberish,
      _market: string,
      _outcome: BigNumberish,
      _amount: BigNumberish,
      _price: BigNumberish,
      _betterOrderId: BytesLike,
      _worseOrderId: BytesLike,
      _tradeGroupId: BytesLike,
      _loopLimit: BigNumberish,
      _fingerprint: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "publicTrade(uint8,address,uint256,uint256,uint256,bytes32,bytes32,bytes32,uint256,bytes32)"(
      _direction: BigNumberish,
      _market: string,
      _outcome: BigNumberish,
      _amount: BigNumberish,
      _price: BigNumberish,
      _betterOrderId: BytesLike,
      _worseOrderId: BytesLike,
      _tradeGroupId: BytesLike,
      _loopLimit: BigNumberish,
      _fingerprint: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    augur(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "augur()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    augurTrading(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "augurTrading()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    cash(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "cash()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    createOrder(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "createOrder()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    fillOrder(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "fillOrder()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getInitialized(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getInitialized()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      _augur: string,
      _augurTrading: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "initialize(address,address)"(
      _augur: string,
      _augurTrading: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    orders(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "orders()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    publicFillBestOrder(
      _direction: BigNumberish,
      _market: string,
      _outcome: BigNumberish,
      _amount: BigNumberish,
      _price: BigNumberish,
      _tradeGroupId: BytesLike,
      _loopLimit: BigNumberish,
      _fingerprint: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "publicFillBestOrder(uint8,address,uint256,uint256,uint256,bytes32,uint256,bytes32)"(
      _direction: BigNumberish,
      _market: string,
      _outcome: BigNumberish,
      _amount: BigNumberish,
      _price: BigNumberish,
      _tradeGroupId: BytesLike,
      _loopLimit: BigNumberish,
      _fingerprint: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    publicTrade(
      _direction: BigNumberish,
      _market: string,
      _outcome: BigNumberish,
      _amount: BigNumberish,
      _price: BigNumberish,
      _betterOrderId: BytesLike,
      _worseOrderId: BytesLike,
      _tradeGroupId: BytesLike,
      _loopLimit: BigNumberish,
      _fingerprint: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "publicTrade(uint8,address,uint256,uint256,uint256,bytes32,bytes32,bytes32,uint256,bytes32)"(
      _direction: BigNumberish,
      _market: string,
      _outcome: BigNumberish,
      _amount: BigNumberish,
      _price: BigNumberish,
      _betterOrderId: BytesLike,
      _worseOrderId: BytesLike,
      _tradeGroupId: BytesLike,
      _loopLimit: BigNumberish,
      _fingerprint: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
