/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface UniverseFactoryInterface extends ethers.utils.Interface {
  functions: {
    "createUniverse(address,bytes32,uint256[])": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "createUniverse",
    values: [string, BytesLike, BigNumberish[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "createUniverse",
    data: BytesLike
  ): Result;

  events: {};
}

export class UniverseFactory extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  listeners<T, G>(
    eventFilter?: TypedEventFilter<T, G>
  ): Array<TypedListener<T, G>>;
  off<T, G>(
    eventFilter: TypedEventFilter<T, G>,
    listener: TypedListener<T, G>
  ): this;
  on<T, G>(
    eventFilter: TypedEventFilter<T, G>,
    listener: TypedListener<T, G>
  ): this;
  once<T, G>(
    eventFilter: TypedEventFilter<T, G>,
    listener: TypedListener<T, G>
  ): this;
  removeListener<T, G>(
    eventFilter: TypedEventFilter<T, G>,
    listener: TypedListener<T, G>
  ): this;
  removeAllListeners<T, G>(eventFilter: TypedEventFilter<T, G>): this;

  queryFilter<T, G>(
    event: TypedEventFilter<T, G>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<T & G>>>;

  interface: UniverseFactoryInterface;

  functions: {
    createUniverse(
      _parentUniverse: string,
      _parentPayoutDistributionHash: BytesLike,
      _payoutNumerators: BigNumberish[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "createUniverse(address,bytes32,uint256[])"(
      _parentUniverse: string,
      _parentPayoutDistributionHash: BytesLike,
      _payoutNumerators: BigNumberish[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  createUniverse(
    _parentUniverse: string,
    _parentPayoutDistributionHash: BytesLike,
    _payoutNumerators: BigNumberish[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "createUniverse(address,bytes32,uint256[])"(
    _parentUniverse: string,
    _parentPayoutDistributionHash: BytesLike,
    _payoutNumerators: BigNumberish[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    createUniverse(
      _parentUniverse: string,
      _parentPayoutDistributionHash: BytesLike,
      _payoutNumerators: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<string>;

    "createUniverse(address,bytes32,uint256[])"(
      _parentUniverse: string,
      _parentPayoutDistributionHash: BytesLike,
      _payoutNumerators: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    createUniverse(
      _parentUniverse: string,
      _parentPayoutDistributionHash: BytesLike,
      _payoutNumerators: BigNumberish[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "createUniverse(address,bytes32,uint256[])"(
      _parentUniverse: string,
      _parentPayoutDistributionHash: BytesLike,
      _payoutNumerators: BigNumberish[],
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    createUniverse(
      _parentUniverse: string,
      _parentPayoutDistributionHash: BytesLike,
      _payoutNumerators: BigNumberish[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "createUniverse(address,bytes32,uint256[])"(
      _parentUniverse: string,
      _parentPayoutDistributionHash: BytesLike,
      _payoutNumerators: BigNumberish[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
