---
env:
  browser: true
  mocha: true
parser: babel-eslint
extends:
- plugin:react/recommended
- plugin:prettier/recommended
- plugin:jest/recommended
- airbnb
- prettier
- prettier/react
- prettier/standard
settings:
  import/resolver:
    webpack:
      extensions:
      - ".js"
      - ".jsx"
      - ".less"
globals:
  assert: true
  jest/globals: true
rules:
  no-eq-null: 0
  no-console: 0
  consistent-return: 0
  global-require: 0
  no-use-before-define: 0
  no-shadow: 0
  prefer-template: 0
  import/prefer-default-export: 0
  no-underscore-dangle: 0
  react/require-default-props: 1
  react/no-multi-comp: 0
  no-prototype-builtins: 0
  no-restricted-globals:
  - 0
  - name: isNaN
  jsx-a11y/anchor-is-valid:
  - 0
  - components:
    - Link
    aspects:
    - noHref
  jsx-a11y/label-has-for:
  - 2
  - components:
    - Label
    required:
      every:
      - nesting
      - id
    allowChildren: true
  import/extensions:
  - 2
  - never
  - styles: always
  import/no-extraneous-dependencies:
  - error
  - devDependencies:
    - "**/*[-.]test.js?(x)"
    - test/**/*.js?(x)
  no-useless-rename: 2
  prefer-arrow-callback: 2
  eqeqeq:
  - 2
  - allow-null
  no-unused-expressions:
  - 2
  - allowShortCircuit: true
  no-unused-vars:
  - 2
  - vars: all
    args: none
  no-param-reassign:
  - 2
  - props: false
  no-plusplus:
  - 2
  - allowForLoopAfterthoughts: true
  prefer-destructuring:
  - 2
  - array: false
    object: true
  jsx-a11y/click-events-have-key-events: 0
  react/no-string-refs: 0
  react/no-unused-prop-types: 1
  react/forbid-prop-types: 0
  react/jsx-filename-extension:
  - 1
  - extensions:
    - ".tsx"
    - ".jsx"
