export const POSITION_CLOSING = 'CLOSING';
export const POSITION_CLOSING_CONFIRMATION = 'CLOSING_CONFIRMATION';
export const POSTION_CLOSED = 'CLOSED';
export const POSITION_CLOSING_FAILED = 'CLOSING_FAILED';
