export const SearchBar: string;
export const searchBar: string;
export const SearchBar__container: string;
export const searchBarContainer: string;
export const SearchBar__containerFocused: string;
export const searchBarContainerFocused: string;
export const isFocused: string;
export const SearchBar__cancel: string;
export const searchBarCancel: string;
