version: '3.5'

volumes:
  nginx-shared:

services:
  nginx:
    image: nginx:1.13-alpine
    hostname: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - nginx-shared:/nginx
    depends_on:
      - web
  db:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
  web:
    image: augurproject/safe-relay-service_web:latest
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - geth
    working_dir: /app
    ports:
      - "8888:8888"
    volumes:
      - nginx-shared:/nginx
    command: docker/web/run_web.sh

  redis:
    image: redis:4-alpine
    ports:
      - "6379:6379"

  worker: &worker
    image: augurproject/safe-relay-service_web:latest
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - geth
    command: docker/web/celery/worker/run.sh

  scheduler:
    <<: *worker
    command: docker/web/celery/scheduler/run.sh

  geth:
    image: augurproject/dev-pop-geth-v2:6e9aed144bf4d54674d91ae169ce5c18
    ports:
      - "8545:8545"

