version: '3.7'

volumes:
  nginx-shared:

services:
  nginx:
    image: nginx:1.13-alpine
    hostname: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - nginx-shared:/nginx
    depends_on:
      - web
    networks:
      - augur
  db:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    networks:
      - augur
  web:
    image: augurproject/safe-relay-service_web:latest
    env_file:
      - .env
    environment:
      - SAFE_CONTRACT_ADDRESS=${GNOSIS_SAFE_CONTRACT_ADDRESS}
      - SAFE_OLD_CONTRACT_ADDRESS=${GNOSIS_SAFE_CONTRACT_ADDRESS}
      - SAFE_PROXY_FACTORY_ADDRESS=${PROXY_FACTORY_CONTRACT_ADDRESS}
    depends_on:
      - db
      - redis
    working_dir: /app
    ports:
      - "8888:8888"
    volumes:
      - nginx-shared:/nginx
    command: docker/web/run_web.sh
    networks:
      - augur

  redis:
    image: redis:4-alpine
    ports:
      - "6379:6379"
    networks:
      - augur

  worker: &worker
    image: augurproject/safe-relay-service_web:latest
    env_file:
      - .env
    environment:
      - SAFE_CONTRACT_ADDRESS=${GNOSIS_SAFE_CONTRACT_ADDRESS}
      - SAFE_OLD_CONTRACT_ADDRESS=${GNOSIS_SAFE_CONTRACT_ADDRESS}
      - SAFE_PROXY_FACTORY_ADDRESS=${PROXY_FACTORY_CONTRACT_ADDRESS}
    depends_on:
      - db
      - redis
      - web
    command: docker/web/celery/worker/run.sh
    networks:
      - augur

  scheduler:
    <<: *worker
    command: docker/web/celery/scheduler/run.sh
    restart: on-failure
    networks:
      - augur

  0x-mesh:
    image: 0xorg/mesh:0xV3
    restart: on-failure
    hostname: 0x
    ports:
      - 60557:60557 # rpc_port_number
      - 60558:60558 # P2PTCPPort
      - 60559:60559 # P2PWebSocketsPort
    environment:
      - ETHEREUM_CHAIN_ID=${ETHEREUM_CHAIN_ID}
      - CUSTOM_CONTRACT_ADDRESSES=${CUSTOM_CONTRACT_ADDRESSES}
      - ETHEREUM_RPC_URL=http://geth:8545
      - USE_BOOTSTRAP_LIST=false
      - BLOCK_POLLING_INTERVAL=1s
      - ETHEREUM_RPC_MAX_REQUESTS_PER_24_HR_UTC=169120 # needed when polling interval is 1s
      - VERBOSITY=4 # 5=debug 6=trace
      - RPC_ADDR=0.0.0.0:60557
    networks:
      - augur
    volumes:
      - ./keys:/usr/mesh/0x_mesh/keys

networks:
  augur:
    name: augur

