export const MODAL_LEDGER = "MODAL_LEDGER";
export const MODAL_TREZOR = "MODAL_TREZOR";
export const MODAL_NETWORK_MISMATCH = "MODAL_NETWORK_MISMATCH";
export const MODAL_NETWORK_CONNECT = "MODAL_NETWORK_CONNECT";
export const MODAL_NETWORK_DISCONNECTED = "MODAL_NETWORK_DISCONNECTED";
export const MODAL_ACCOUNT_APPROVAL = "MODAL_ACCOUNT_APPROVAL";
export const MODAL_CLAIM_REPORTING_FEES_FORKED_MARKET =
  "MODAL_CLAIM_REPORTING_FEES_FORKED_MARKET";
export const MODAL_CLAIM_REPORTING_FEES_NONFORKED_MARKETS =
  "MODAL_CLAIM_REPORTING_FEES_NONFORKED_MARKETS";
export const MODAL_PARTICIPATE = "MODAL_PARTICIPATE";
export const MODAL_MIGRATE_MARKET = "MODAL_MIGRATE_MARKET";
export const MODAL_NETWORK_DISABLED = "MODAL_NETWORK_DISABLED";
export const MODAL_DISCLAIMER = "MODAL_DISCLAIMER";
export const MODAL_MARKET_REVIEW = "MODAL_MARKET_REVIEW";
export const MODAL_CONFIRM = "MODAL_CONFIRM";
export const MODAL_REVIEW = "MODAL_REVIEW";
export const MODAL_GAS_PRICE = "MODAL_GAS_PRICE";
export const MODAL_CLAIM_TRADING_PROCEEDS = "MODAL_CLAIM_TRADING_PROCEEDS";
