export const BUY = 'buy'
export const SELL = 'sell'
export const BUY_UP = 'buyUp'
export const BUY_DOWN = 'buyDown'
export const SELL_UP = 'sellUp'
export const SELL_DOWN = 'sellDown'
export const NONE = 'none'
