export const FILTER_SEARCH_PARAM = 'keywords'
export const FILTER_MARKET_STATE_PARAM = 'market-state'
export const SORT_MARKET_PARAM = 'market-sort-param'
export const SORT_MARKET_ORDER_PARAM = 'market-sort-order'
export const TAGS_PARAM_NAME = 'tags'
export const TOPIC_PARAM_NAME = 'topic'
