version: '3.7'

services:
  0x-mesh-standalone:
    image: 0xorg/mesh:${MESH_VERSION}
    restart: on-failure
    hostname: 0x
    ports:
      - 60557:60557 # rpc_port_number
      - 60558:60558 # P2PTCPPort
      - 60559:60559 # P2PWebSocketsPort
    environment:
      - ETHEREUM_CHAIN_ID=${ETHEREUM_CHAIN_ID}
      - CUSTOM_CONTRACT_ADDRESSES=${CUSTOM_CONTRACT_ADDRESSES}
      - VERBOSITY=${MESH_VERBOSITY:-4} # 5=debug 6=trace
      - CUSTOM_ORDER_FILTER={"properties":{"makerAssetData":{"pattern":".*${ZEROX_CONTRACT_ADDRESS}.*"}}}
      - ETHEREUM_RPC_URL=${ETHEREUM_RPC_HTTP}
      - USE_BOOTSTRAP_LIST=true
      - BLOCK_POLLING_INTERVAL=1s
      - ETHEREUM_RPC_MAX_REQUESTS_PER_24_HR_UTC=169120 # needed when polling interval is 1s
      - WS_RPC_ADDR=0.0.0.0:60557
