export const INVALID_USERNAME_OR_PASSWORD = 403;
export const PASSWORD_TOO_SHORT = 405;
export const USERNAME_TAKEN = 422;
export const USERNAME_REQUIRED = 'USERNAME_REQUIRED';
export const PASSWORDS_DO_NOT_MATCH = 'PASSWORDS_DO_NOT_MATCH';

export const INVALID_USERNAME = 'INVALID_USERNAME';
export const INVALID_USER = 'INVALID_USER';
