env:
  global:
    - secure: "B0vgd3/83+GeQXtpNKAfVpNh+PQ2zV8Xa6uNevBF8cTFc5lPLtE7dOxLl5i5gkXgpcWCeoG7dN8vaplePYgxciJUOb8amFe6dOE/qtX+dUiv08kmu7XTYFuQlLX3kFzRgfvNN/gEslJrVLFTUJuxP+FdGJzFdceN9ytkJsfCDds+a0npMi5QsgHQ4IWemTQ+9mF78sL0OkTeV5sZMACFA8Bm7bb3o8Xo679nkdS0+BiAKA4CoZuQ/E/5ivmpUi3d2M9vk7Y74fKus5slNeM8jax1z6n3C/mJN9s7pGFph3jUWd0UhssGvbp/X2O5Wnh2nnVaPYWMhyyE4bsQWpj9xE/URZYYOEX+YAc/E3+SYfOh0zU6E+DuI6aZQ/Z9LhGvmNBq5OCd0PUw4VXZrXAQqSIYfFLeTMgkW7fa7rJRxn+TF7GU9Yeuqv07eT/2fIgfvNKtj6hJsXdqpcU/IAsavkZ4+0Pf9CpJwmTemBLzZyaP/nDHBwz/c5OWJx2W6KFjdI/1+orI9Y/0DGbSpNK1wcUFEMk9+Qm1crE7lmxzSP0dQ3FpsRpq2uSrq/EwYMxTsYyfa7uhlExXYFcTYilmSdMyGII2mSNzkw0LHcjYb8mNpfW0ZHV3Y5xe0mXz7Zg407bLN29KQnTemDvw2/aX5xTOsQFzwacdLtlNkKJ3K64="
    - secure: "yY8Ky8QVFsJtMlBhmNOqmuSAKddRZWeFA62FvkzF4PEAWLKGAQy5cOjzEicCQdhTiOC/oM3LWkLVH85OcQIaE7Z8IGmXzEJPlFs7w4DjU2vaSwWOt3n2IbgxuBKBRolEUByZHGai9oqe1WcM61fVh2GEuaAk/8JbBHslT8C6A47Uzsja0gHTZZQq90JRpOX6O+joe+ZBH7z0MV/oY2E6GGa75bVBFiZptuqcB1rWFdT5b6tHEMDJ1Of2A4yNfF52j5Lk+HWNVARFSO0IPxpcX763vaeiYQ/OLuzlBtN7K7aQizONw8pg/1ukQYAmOu+eQtQj3pTXCL0H3f8msNql4ksJlHXkHWJr1eYO+vpZr9xjCLs29fHTJQYl+QHqG/pOJKIMoCDQruUZwFcS8Yu3ZY8evugM0Sz9BHkKgaUVAxpyuurkDuUaHA4IQu05IbBbj5VwP4QHDwpvI/VMM4mrFmUIeW73GDFfvsAs6U635XzVEvE7IleN5nmkxTBh1vxH436xhmMPYWAoRwpI/LTA5/pNut4H2EyFNybotpPzy1oloAH/u7uw57oNbA/UKtxwaUtEp7n95Aqba+cr9xYJ48kY8Ro/GmIeXOW1GJC7r4qCbnmUr5tPlqtaGwDClzKpLJ9D6rc6GC5aO1iUnhbL+pHCbGBA8L7a4Q4zZihD3HA="
    - secure: "fPJbL9XxBhH8Qxs82/fZ2PsHhrYfhlKR6FA+Nf/qcGuKL9Eo/YGa+TXtE9GA85Dwe8+ugI9sFfMoZvNuS4uAGbqI50fLKWtvQkQhfmEHc7bSgXUSsDGJipkRXpQu2O92YVsEjL0HG8f2w5WQ3hSCktKl4RChB4WFHX3ZlRRrFzN6jIkMDliiKFUsF2Zgjl1Us8iLsHNfNHjNa7vUkIAVAWFr0Mv6p/QFFo6MgnhsZo6ISi9eggP+J/URyB/Ei7vM4H6oaD86TYw3wW6IGFz7v6XU+rVUW2zDKu+H04G6+U8QIx//v5Gjms0xkp7VOKsL7ydOkqzvp1IaxT2eBvJFdqJNKSYCZTftH7/ZZfMvlMd0xef9Tv2oabUxqNBQ4ITH8mWIRIASl/KCnPGXE9DRBnfPWBnGDjXTKEZ5hz2XMvLWL52uf5LIvrG4gN2pAcv4KNhT33nxfxKS9jwBSfnUlvD3asaH0+r4T8ljgKdOItWYE3GW5NCG5x8ARJHWC9ebdyyk+Dvrhgx1Yny3V/9Dr4FxHKObDgkVHNxFfnc4RdNQlzHml7lqVISnb/EEaAOLcpzszyrx03fvwADJ3+hsOg1Ud9F9zWBf41pjQAHmsJYjmJhNg+mRFSU97HNZZVSvAlRxyYP4Xxx1qXKfRXBtqnwVJqLvK6JTpIlh4WH28ko="
notifications:
  email: false
branches:
  only:
  - master
  - electron-build
  - "/release-\\d+\\.\\d+\\.\\d+(-\\w+\\.\\d)?$/"
  - petong/ch13701/publish-installer-checksums-for-users-to
cache:
    directories:
        - $HOME/.cache/electron-builder


matrix:
  include:
  - os: linux
    language: node_js
    node_js: "9"
    sudo: required
    language: generic

  - os: osx
    osx_image: xcode9.3
    language: node_js
    node_js: "9"
    env:
      - CSC_LINK=certs/mac.p12
      - secure: "oZ3OGN4i7s4hENVOBB63XAmhFwN1aY8AnMHt+KrLQv8FMdGvPdUI0gXfcYZfV4mfT5BPoT5cnbdrxduV9cuj1nc/jB6F18hfBV4ftI8TXYnlOnJUbpOrpy6YNXC30mmL6P8fzEMHXfABTr8zrHy4IPBniVPWPGGDMw446ZikcL2uLwS2k90c6dT4WOY3uTeLt1eq9Nyi7t+e4VstHXEXFHz5lngVO4og4494ssPhFc0UajycnpH58PJU4UaZF8oc0ZHavUjbEgwb2oMirrDnS290KINFw27RoDAW75zdL0s/ujm9CEj34bGAH/NmrFeVGL/a/YFtLWZDKJRlfMlukug9SmMQEbAb6fvcst7n/K5bQ7oUcKGY3vC+N1UYnQzdxZ0o4XWWfUKmAox9eDItCV4ZXECq3HhrkrJMIBJ+4pZ0hA1ipULZ4gglO99MjktdH8inyDQ9WiM7Xz6lHQFVF98lFqUP0pnUIdSQIJOfwJ+QjnPHfSx4WWqn9nuZPoEqc6Ehp0UsG9EB8ZmcLrh2Q4tROrifmF6It3S2sKM79SB9m+d1/GUjANE4oS7txk+8Au9UY5/XsbreLQ3/GVEJasNSudm6MNYCT1TcB6aCWfT13BWhnTHix2nBMUpYDGSRzFTb/NH9d2gOl7R6VS+8FWcu69WE6wYKKyLyHB4LZHg="

before_install:
  - openssl aes-256-cbc -K $encrypted_77e0d3261394_key -iv $encrypted_77e0d3261394_iv -in certs/mac.p12.enc -out certs/mac.p12 -d

script:
 - scripts/electron-build.sh
