/**
 * Values used to indicate the 'level' of a notification.
 * These will be used to route notifications across the various notification displays.
 * Different level might also indicate different behaviors.e.g. Critical blocks the ui and must be dismissed to continue.
 *
 * @readonly
 * @enum {string}
 */
export const CRITICAL = "CRITICAL";
export const INFO = "INFO";
export const CREATEGENESISUNIVERSE = "CREATEGENESISUNIVERSE";
export const CANCELORPHANEDORDER = "CANCELORPHANEDORDER";
export const CANCELORDER = "CANCELORDER";
export const WITHDRAWETHERTOIFPOSSIBLE = "WITHDRAWETHERTOIFPOSSIBLE";
export const CALCULATEREPORTINGFEE = "CALCULATEREPORTINGFEE";
export const CLAIMTRADINGPROCEEDS = "CLAIMTRADINGPROCEEDS";
export const PUBLICBUYCOMPLETESETS = "PUBLICBUYCOMPLETESETS";
export const PUBLICBUYCOMPLETESETSWITHCASH = "PUBLICBUYCOMPLETESETSWITHCASH";
export const PUBLICSELLCOMPLETESETS = "PUBLICSELLCOMPLETESETS";
export const PUBLICSELLCOMPLETESETSWITHCASH = "PUBLICSELLCOMPLETESETSWITHCASH";
export const PUBLICCREATEORDER = "PUBLICCREATEORDER";
export const BUYPARTICIPATIONTOKENS = "BUYPARTICIPATIONTOKENS";
export const PUBLICFILLBESTORDER = "PUBLICFILLBESTORDER";
export const PUBLICFILLBESTORDERWITHLIMIT = "PUBLICFILLBESTORDERWITHLIMIT";
export const PUBLICFILLORDER = "PUBLICFILLORDER";
export const MIGRATEREP = "MIGRATEREP";
export const WITHDRAWETHER = "WITHDRAWETHER";
export const WITHDRAWTOKENS = "WITHDRAWTOKENS";
export const CONTRIBUTE = "CONTRIBUTE";
export const DISAVOWCROWDSOURCERS = "DISAVOWCROWDSOURCERS";
export const DOINITIALREPORT = "DOINITIALREPORT";
export const FINALIZE = "FINALIZE";
export const FINALIZEFORK = "FINALIZEFORK";
export const MIGRATETHROUGHONEFORK = "MIGRATETHROUGHONEFORK";
export const MIGRATEBALANCESFROMLEGACYREP = "MIGRATEBALANCESFROMLEGACYREP";
export const MIGRATEALLOWANCESFROMLEGACYREP = "MIGRATEALLOWANCESFROMLEGACYREP";
export const MIGRATEIN = "MIGRATEIN";
export const MIGRATEOUT = "MIGRATEOUT";
export const MIGRATEOUTBYPAYOUT = "MIGRATEOUTBYPAYOUT";
export const UPDATEPARENTTOTALTHEORETICALSUPPLY =
  "UPDATEPARENTTOTALTHEORETICALSUPPLY";
export const UPDATESIBLINGMIGRATIONTOTAL = "UPDATESIBLINGMIGRATIONTOTAL";
export const PUBLICBUY = "PUBLICBUY";
export const PUBLICBUYWITHLIMIT = "PUBLICBUYWITHLIMIT";
export const PUBLICSELL = "PUBLICSELL";
export const PUBLICSELLWITHLIMIT = "PUBLICSELLWITHLIMIT";
export const PUBLICTRADE = "PUBLICTRADE";
export const PUBLICTRADEWITHLIMIT = "PUBLICTRADEWITHLIMIT";
export const FAUCET = "FAUCET";
export const CLAIMSHARESINUPDATE = "CLAIMSHARESINUPDATE";
export const GETFROZENSHAREVALUEINMARKET = "GETFROZENSHAREVALUEINMARKET";
export const CREATEMARKET = "CREATEMARKET";
export const CREATECATEGORICALMARKET = "CREATECATEGORICALMARKET";
export const CREATESCALARMARKET = "CREATESCALARMARKET";
export const CREATEYESNOMARKET = "CREATEYESNOMARKET";
export const CREATECHILDUNIVERSE = "CREATECHILDUNIVERSE";
export const FORK = "FORK";
export const REDEEMSTAKE = "REDEEMSTAKE";
export const GETINITIALREPORTSTAKESIZE = "GETINITIALREPORTSTAKESIZE";
export const GETORCACHEDESIGNATEDREPORTNOSHOWBOND =
  "GETORCACHEDESIGNATEDREPORTNOSHOWBOND";
export const GETORCACHEDESIGNATEDREPORTSTAKE =
  "GETORCACHEDESIGNATEDREPORTSTAKE";
export const GETORCACHEMARKETCREATIONCOST = "GETORCACHEMARKETCREATIONCOST";
export const GETORCACHEREPORTINGFEEDIVISOR = "GETORCACHEREPORTINGFEEDIVISOR";
export const GETORCACHEVALIDITYBOND = "GETORCACHEVALIDITYBOND";
export const GETORCREATECURRENTFEEWINDOW = "GETORCREATECURRENTFEEWINDOW";
export const GETORCREATEFEEWINDOWBYTIMESTAMP =
  "GETORCREATEFEEWINDOWBYTIMESTAMP";
export const GETORCREATENEXTFEEWINDOW = "GETORCREATENEXTFEEWINDOW";
export const GETORCREATEPREVIOUSFEEWINDOW = "GETORCREATEPREVIOUSFEEWINDOW";
export const UPDATEFORKVALUES = "UPDATEFORKVALUES";
export const APPROVE = "APPROVE";
export const DECREASEAPPROVAL = "DECREASEAPPROVAL";
export const DEPOSITETHER = "DEPOSITETHER";
export const DEPOSITETHERFOR = "DEPOSITETHERFOR";
export const FORKANDREDEEM = "FORKANDREDEEM";
export const REDEEMFORREPORTINGPARTICIPANT = "REDEEMFORREPORTINGPARTICIPANT";
export const REDEEM = "REDEEM";
export const INCREASEAPPROVAL = "INCREASEAPPROVAL";
export const MIGRATE = "MIGRATE";
export const TRANSFER = "TRANSFER";
export const TRANSFERFROM = "TRANSFERFROM";
export const TRANSFEROWNERSHIP = "TRANSFEROWNERSHIP";
export const WITHDRAWETHERTO = "WITHDRAWETHERTO";
export const WITHDRAWINEMERGENCY = "WITHDRAWINEMERGENCY";
export const SENDETHER = "SENDETHER";
export const SENDREPUTATION = "SENDREPUTATION";
